package com.omnihub.source.core

/**
 * Canonical WEB provider registry used for URL resolution and Store seeding.
 * All entries use the universal WebView PageSensor path — no per-site hardcoded buttons.
 */
object ProviderCatalog {

    data class Entry(
        val id: String,
        val name: String,
        val url: String,
        val kind: String = "WEB" // WEB or MCP
    )

    val ALL: List<Entry> = listOf(
        // Core AI chats
        Entry("chatgpt", "ChatGPT", "https://chatgpt.com"),
        Entry("claude", "Claude", "https://claude.ai"),
        Entry("gemini", "Gemini", "https://gemini.google.com/app"),
        Entry("perplexity", "Perplexity", "https://www.perplexity.ai"),
        Entry("deepseek", "DeepSeek", "https://chat.deepseek.com"),
        Entry("grok", "Grok", "https://x.com/i/grok"),
        Entry("groq", "Groq", "https://chat.groq.com"),
        Entry("kimi", "Kimi", "https://kimi.moonshot.cn"),
        Entry("zai", "Z.AI", "https://chat.z.ai"),
        Entry("qwen", "Qwen", "https://chat.qwen.ai"),
        Entry("mistral", "Le Chat", "https://chat.mistral.ai"),
        Entry("pi", "Pi", "https://pi.ai"),
        Entry("poe", "Poe", "https://poe.com"),
        Entry("you", "You.com", "https://you.com"),
        Entry("phind", "Phind", "https://www.phind.com"),
        Entry("character", "Character.AI", "https://character.ai"),
        Entry("huggingface", "HuggingChat", "https://huggingface.co/chat"),
        Entry("cohere", "Cohere", "https://coral.cohere.com"),
        Entry("meta_ai", "Meta AI", "https://www.meta.ai"),
        Entry("bing", "Copilot", "https://copilot.microsoft.com"),
        Entry("duckduckgo_ai", "Duck.ai", "https://duck.ai"),
        Entry("lmsys", "LMSYS Chatbot Arena", "https://chat.lmsys.org"),
        Entry("openrouter", "OpenRouter", "https://openrouter.ai/chat"),
        Entry("together", "Together", "https://api.together.xyz/playground"),
        Entry("fireworks", "Fireworks", "https://fireworks.ai"),
        Entry("replicate", "Replicate", "https://replicate.com"),
        Entry("nvidia_nim", "NVIDIA NIM", "https://build.nvidia.com"),
        Entry("sambanova", "SambaNova", "https://cloud.sambanova.ai"),
        Entry("cerebras", "Cerebras", "https://inference.cerebras.ai"),
        Entry("ai21", "AI21", "https://studio.ai21.com"),
        Entry("writer", "Writer", "https://app.writer.com"),
        Entry("jasper", "Jasper", "https://app.jasper.ai"),
        Entry("copy_ai", "Copy.ai", "https://app.copy.ai"),
        Entry("notion_ai", "Notion AI", "https://www.notion.so"),
        Entry("coda_ai", "Coda AI", "https://coda.io"),
        Entry("mem", "Mem", "https://mem.ai"),
        Entry("reflect", "Reflect", "https://reflect.app"),
        Entry("obsidian_sync", "Obsidian", "https://obsidian.md"),
        Entry("cursor", "Cursor", "https://cursor.com"),
        Entry("v0", "v0", "https://v0.dev"),
        Entry("bolt", "Bolt", "https://bolt.new"),
        Entry("lovable", "Lovable", "https://lovable.dev"),
        Entry("replit", "Replit Agent", "https://replit.com"),
        Entry("claude_code", "Claude", "https://claude.ai"),
        Entry("devin", "Devin", "https://app.devin.ai"),
        Entry("windsurf", "Windsurf", "https://windsurf.com"),
        Entry("sourcegraph", "Sourcegraph", "https://sourcegraph.com"),
        Entry("tabnine", "Tabnine", "https://www.tabnine.com"),
        Entry("codeium", "Codeium", "https://codeium.com"),
        Entry("continue_dev", "Continue", "https://continue.dev"),
        Entry("aistudio", "Google AI Studio", "https://aistudio.google.com"),
        Entry("vertex", "Vertex AI", "https://console.cloud.google.com/vertex-ai"),
        Entry("azure_ai", "Azure AI", "https://ai.azure.com"),
        Entry("aws_bedrock", "Bedrock", "https://console.aws.amazon.com/bedrock"),
        Entry("ibm_watsonx", "watsonx", "https://dataplatform.cloud.ibm.com"),
        Entry("oracle_ai", "Oracle AI", "https://www.oracle.com/artificial-intelligence"),
        Entry("salesforce_einstein", "Einstein", "https://www.salesforce.com"),
        Entry("zendesk_ai", "Zendesk AI", "https://www.zendesk.com"),
        Entry("intercom", "Intercom", "https://www.intercom.com"),
        Entry("freshdesk", "Freshdesk", "https://www.freshworks.com"),
        Entry("slack", "Slack", "https://app.slack.com"),
        Entry("discord", "Discord", "https://discord.com/app"),
        Entry("telegram", "Telegram Web", "https://web.telegram.org"),
        Entry("whatsapp", "WhatsApp Web", "https://web.whatsapp.com"),
        Entry("gmail", "Gmail", "https://mail.google.com"),
        Entry("outlook", "Outlook", "https://outlook.live.com"),
        Entry("calendar_google", "Google Calendar", "https://calendar.google.com"),
        Entry("drive", "Google Drive", "https://drive.google.com"),
        Entry("dropbox", "Dropbox", "https://www.dropbox.com"),
        Entry("notion", "Notion", "https://www.notion.so"),
        Entry("linear", "Linear", "https://linear.app"),
        Entry("jira", "Jira", "https://www.atlassian.com/software/jira"),
        Entry("github", "GitHub", "https://github.com"),
        Entry("gitlab", "GitLab", "https://gitlab.com"),
        Entry("figma", "Figma", "https://www.figma.com"),
        Entry("canva", "Canva", "https://www.canva.com"),
        Entry("midjourney", "Midjourney", "https://www.midjourney.com"),
        Entry("leonardo", "Leonardo", "https://app.leonardo.ai"),
        Entry("ideogram", "Ideogram", "https://ideogram.ai"),
        Entry("runway", "Runway", "https://app.runwayml.com"),
        Entry("pika", "Pika", "https://pika.art"),
        Entry("suno", "Suno", "https://suno.com"),
        Entry("udio", "Udio", "https://www.udio.com"),
        Entry("elevenlabs", "ElevenLabs", "https://elevenlabs.io"),
        Entry("descript", "Descript", "https://www.descript.com"),
        Entry("otter", "Otter", "https://otter.ai"),
        Entry("fireflies", "Fireflies", "https://fireflies.ai"),
        Entry("grain", "Grain", "https://grain.com"),
        Entry("gamma", "Gamma", "https://gamma.app"),
        Entry("tome", "Tome", "https://tome.app"),
        Entry("beautiful_ai", "Beautiful.ai", "https://www.beautiful.ai"),
        Entry("chatpdf", "ChatPDF", "https://www.chatpdf.com"),
        Entry("humata", "Humata", "https://www.humata.ai"),
        Entry("explainpaper", "ExplainPaper", "https://www.explainpaper.com"),
        Entry("elicit", "Elicit", "https://elicit.com"),
        Entry("consensus", "Consensus", "https://consensus.app"),
        Entry("scite", "Scite", "https://scite.ai"),
        Entry("researchrabbit", "ResearchRabbit", "https://www.researchrabbit.ai"),
        Entry("connectedpapers", "Connected Papers", "https://www.connectedpapers.com"),
        Entry("semanticscholar", "Semantic Scholar", "https://www.semanticscholar.org"),
        Entry("arxiv", "arXiv", "https://arxiv.org"),
        Entry("wolfram", "Wolfram Alpha", "https://www.wolframalpha.com"),
        Entry("desmos", "Desmos", "https://www.desmos.com"),
        Entry("khanmigo", "Khanmigo", "https://www.khanmigo.ai"),
        Entry("duolingo", "Duolingo", "https://www.duolingo.com"),
        Entry("grammarly", "Grammarly", "https://app.grammarly.com"),
        Entry("quillbot", "QuillBot", "https://quillbot.com"),
        Entry("deepl", "DeepL", "https://www.deepl.com/translator"),
        Entry("translate_google", "Google Translate", "https://translate.google.com"),
        // MCP-style productivity cores (still open in WebView for auth/actions)
        Entry("mcp_files", "Files MCP", "https://drive.google.com", "MCP"),
        Entry("mcp_calendar", "Calendar MCP", "https://calendar.google.com", "MCP"),
        Entry("mcp_mail", "Mail MCP", "https://mail.google.com", "MCP"),
        Entry("mcp_github", "GitHub MCP", "https://github.com", "MCP"),
        Entry("mcp_slack", "Slack MCP", "https://app.slack.com", "MCP"),
        Entry("mcp_notion", "Notion MCP", "https://www.notion.so", "MCP"),
        Entry("mcp_linear", "Linear MCP", "https://linear.app", "MCP"),
        Entry("mcp_jira", "Jira MCP", "https://www.atlassian.com", "MCP"),
        Entry("mcp_figma", "Figma MCP", "https://www.figma.com", "MCP"),
        Entry("mcp_browser", "Browser MCP", "https://www.google.com", "MCP")
    )

    fun urlFor(id: String): String? =
        ALL.find { it.id.equals(id, true) || id.contains(it.id, true) }?.url

    fun nameFor(id: String): String? =
        ALL.find { it.id.equals(id, true) }?.name

    fun webEntries(): List<Entry> = ALL.filter { it.kind == "WEB" }
    fun mcpEntries(): List<Entry> = ALL.filter { it.kind == "MCP" }
}
