package com.omnihub.source.core

import android.annotation.SuppressLint
import android.content.Context
import android.os.Handler
import android.os.Looper
import android.util.Log
import android.webkit.JavascriptInterface
import kotlinx.coroutines.suspendCancellableCoroutine
import java.util.UUID
import kotlin.coroutines.resume

/**
 * Web Interaction Engine 1.0.9.4
 * Per-provider queue, MutationObserver stream, single-send, layout memory, latency logs.
 */
object WebViewChatEngine {

    data class Result(val text: String, val ok: Boolean, val transactionId: String = "")

    private const val TAG = "WEB"

    private val CHROME_LINE = Regex(
        """^(chat|agent|new chat|sign in|sign up|log in|api|terms of service|privacy policy|deep think|max|generated by ai\.?|for reference only\.?|glm[-\d.a-z]+|what can i build|menu|settings|home|upgrade|subscribe|download app|get the app)$""",
        RegexOption.IGNORE_CASE
    )

    fun cleanReply(raw: String, userMessage: String): String? {
        var text = raw.trim()
        val um = userMessage.trim()
        if (um.isNotEmpty() && text.startsWith(um)) {
            text = text.removePrefix(um).trim()
        }
        val lines = text.lines().map { it.trim() }.filter { it.isNotEmpty() }
        val filtered = lines.filterNot { CHROME_LINE.matches(it) }
            .filterNot { it.equals(um, ignoreCase = true) }
        text = filtered.joinToString("\n").trim()
        if (text.length < 1) return null
        val lower = text.lowercase()
        val chromeHits = listOf(
            "terms of service", "privacy policy", "sign in", "new chat",
            "generated by ai", "for reference only"
        ).count { it in lower }
        if (chromeHits >= 2 && text.length < 400) return null
        return text
    }

    suspend fun send(
        context: Context,
        siteUrl: String,
        providerId: String,
        userMessage: String,
        timeoutMs: Long = 180_000L,
        onPartial: (String) -> Unit = {}
    ): Result {
        return ProviderRelayQueue.withProviderLock(providerId) { queueWaitMs ->
            sendExclusive(context, siteUrl, providerId, userMessage, timeoutMs, queueWaitMs, onPartial)
        }
    }

    @SuppressLint("SetJavaScriptEnabled")
    private suspend fun sendExclusive(
        context: Context,
        siteUrl: String,
        providerId: String,
        userMessage: String,
        timeoutMs: Long,
        queueWaitMs: Long,
        onPartial: (String) -> Unit
    ): Result = suspendCancellableCoroutine { cont ->
        val main = Handler(Looper.getMainLooper())
        val appCtx = context.applicationContext
        val txn = UUID.randomUUID().toString().take(8).uppercase()
        val t0 = System.currentTimeMillis()
        val learnedIn = InteractionMemory.inputSelector(appCtx, providerId).orEmpty()
        val learnedSend = InteractionMemory.sendSelector(appCtx, providerId).orEmpty()
        val target = siteUrl.ifBlank {
            ProviderCatalog.urlFor(providerId) ?: "https://chatgpt.com/"
        }

        Log.i(TAG, "[$txn] CREATED provider=$providerId queueWaitMs=$queueWaitMs")

        main.post {
            val session = WarmSessionPool.getOrCreate(appCtx, providerId)
            session.busy = true
            session.lastTransactionId = txn
            session.lastUsedAt = System.currentTimeMillis()
            val web = session.web
            var finished = false
            var injected = false
            var firstTokenAt = 0L

            lateinit var timeoutRunnable: Runnable

            fun complete(text: String, ok: Boolean) {
                if (finished) return
                finished = true
                session.busy = false
                try { main.removeCallbacks(timeoutRunnable) } catch (_: Exception) {}
                try {
                    web.evaluateJavascript(
                        "(function(){window.__omniRunning=false;" +
                            "if(window.__omniObs){try{window.__omniObs.disconnect()}catch(e){} window.__omniObs=null;}" +
                            "if(window.__omniTimer){clearInterval(window.__omniTimer);window.__omniTimer=null;}})();",
                        null
                    )
                } catch (_: Exception) {}
                if (!ok) {
                    InteractionMemory.markFailure(appCtx, providerId, "in")
                    InteractionMemory.markFailure(appCtx, providerId, "send")
                }
                val total = System.currentTimeMillis() - t0
                Log.i(
                    TAG,
                    "[$txn] ${if (ok) "DELIVERED" else "FAILURE"} len=${text.length} " +
                        "totalMs=$total queueMs=$queueWaitMs firstTokenMs=${if (firstTokenAt > 0) firstTokenAt - t0 else -1}"
                )
                if (cont.isActive) cont.resume(Result(text, ok, txn))
            }

            timeoutRunnable = Runnable {
                web.evaluateJavascript(
                    "(function(){var n=document.querySelectorAll('[data-message-author-role=\\'assistant\\'],[data-role=\\'assistant\\'],.markdown.prose,.prose');" +
                        "if(!n.length)return '';return (n[n.length-1].innerText||'').trim().slice(0,12000);})();"
                ) { last ->
                    val t = last?.trim()?.removeSurrounding("\"")
                        ?.replace("\\n", "\n")
                        ?.replace("\\\"", "\"")
                        ?.trim().orEmpty()
                    if (t.length > 20) {
                        val cleaned = cleanReply(t, userMessage) ?: t
                        complete(ReplySanitizer.strip(cleaned).ifBlank { cleaned }, true)
                    } else {
                        complete(
                            "Timed out waiting for the model (txn $txn). Stay on the signed-in chat page and retry.",
                            false
                        )
                    }
                }
            }

            val bridgeName = "OmniBridge"
            try { web.removeJavascriptInterface(bridgeName) } catch (_: Exception) {}

            val bridge = object {
                @JavascriptInterface
                fun onReply(text: String) {
                    main.post {
                        val t = text.trim()
                        when {
                            t.startsWith("ERR:") ->
                                complete(t.removePrefix("ERR:").ifBlank { "Page error" }, false)
                            t.isBlank() ->
                                complete("Empty reply from page.", false)
                            else -> {
                                val cleaned = cleanReply(t, userMessage) ?: t
                                val stripped = ReplySanitizer.strip(cleaned)
                                complete(stripped.ifBlank { cleaned }, true)
                            }
                        }
                    }
                }

                @JavascriptInterface
                fun onLearn(inputSel: String?, sendSel: String?) {
                    main.post {
                        InteractionMemory.remember(appCtx, providerId, inputSel, sendSel)
                    }
                }

                @JavascriptInterface
                fun onPartial(text: String) {
                    main.post {
                        if (finished) return@post
                        val raw = text.trim()
                        if (raw.isEmpty() || raw.startsWith("ERR:")) return@post
                        if (firstTokenAt == 0L) {
                            firstTokenAt = System.currentTimeMillis()
                            Log.i(TAG, "[$txn] FIRST_TOKEN +${firstTokenAt - t0}ms")
                        }
                        val cleaned = cleanReply(raw, userMessage) ?: raw
                        val stripped = ReplySanitizer.strip(cleaned)
                        if (stripped.isNotBlank()) onPartial(stripped)
                    }
                }

                @JavascriptInterface
                fun onState(state: String) {
                    Log.i(TAG, "[$txn] $state +${System.currentTimeMillis() - t0}ms")
                }
            }
            web.addJavascriptInterface(bridge, bridgeName)

            cont.invokeOnCancellation {
                main.post {
                    session.busy = false
                    if (!finished) complete("Cancelled", false)
                }
            }

            main.postDelayed(timeoutRunnable, timeoutMs)

            fun inject() {
                if (finished || injected) return
                injected = true
                Log.i(TAG, "[$txn] INJECT +${System.currentTimeMillis() - t0}ms")
                web.evaluateJavascript(
                    "(function(){window.__omniRunning=false;" +
                        "if(window.__omniObs){try{window.__omniObs.disconnect()}catch(e){} window.__omniObs=null;}" +
                        "if(window.__omniTimer){clearInterval(window.__omniTimer);window.__omniTimer=null;}})();",
                    null
                )
                main.postDelayed({
                    if (finished) return@postDelayed
                    web.evaluateJavascript(
                        buildEngineScript(userMessage, learnedIn, learnedSend, txn),
                        null
                    )
                }, 16)
            }

            fun waitComposerThenInject(attempt: Int) {
                if (finished || injected) return
                val learnedCheck = if (learnedIn.isNotBlank())
                    "try{var le=document.querySelector(${org.json.JSONObject.quote(learnedIn)});if(le)learned=true;}catch(e){}"
                else ""
                val checkJs =
                    "(function(){var learned=false;$learnedCheck" +
                        "var n=document.querySelectorAll('textarea,[contenteditable=true],div[role=textbox],#prompt-textarea,.ProseMirror').length;" +
                        "var body=(document.body&&document.body.innerText||'').slice(0,1200).toLowerCase();" +
                        "var auth=/sign in to continue|log in to continue|create an account|enter your password/.test(body);" +
                        "var pw=!!document.querySelector('input[type=password]');" +
                        "return (learned?1:0)+':'+n+':'+(auth||pw?1:0);})();"
                web.evaluateJavascript(checkJs) { countStr ->
                    val cleaned = (countStr ?: "0:0:0").replace("\"", "").trim()
                    val parts = cleaned.split(":")
                    val learnedOk = parts.getOrNull(0)?.toIntOrNull() == 1
                    val n = parts.getOrNull(1)?.toIntOrNull() ?: 0
                    val auth = parts.getOrNull(2)?.toIntOrNull() == 1
                    if (auth && n == 0 && !learnedOk) {
                        complete(
                            "Not signed in. Providers → open this source → Sign in → stay on the chat box → Back.",
                            false
                        )
                        return@evaluateJavascript
                    }
                    if (learnedOk || n > 0) inject()
                    else if (attempt >= 30) inject()
                    else main.postDelayed({ waitComposerThenInject(attempt + 1) }, 100)
                }
            }

            val sameHost = try {
                val a = java.net.URI(target).host?.lowercase().orEmpty()
                val b = java.net.URI(session.lastUrl.ifBlank { "http://local" }).host?.lowercase().orEmpty()
                a.isNotBlank() && (a == b || b.endsWith(a) || a.endsWith(b))
            } catch (_: Exception) {
                false
            }

            if (session.ready && sameHost && session.lastUrl.isNotBlank()) {
                Log.i(TAG, "[$txn] FAST_PATH url=${session.lastUrl}")
                waitComposerThenInject(0)
            } else {
                session.ready = false
                Log.i(TAG, "[$txn] LOAD $target")
                web.webViewClient = object : android.webkit.WebViewClient() {
                    override fun onPageFinished(view: android.webkit.WebView?, url: String?) {
                        session.lastUrl = url.orEmpty()
                        session.ready = true
                        main.postDelayed({ waitComposerThenInject(0) }, 200)
                    }
                }
                web.loadUrl(target)
            }
        }
    }

    private fun buildEngineScript(
        message: String,
        learnedIn: String,
        learnedSend: String,
        txn: String
    ): String {
        val jsonMsg = org.json.JSONObject.quote(message)
        val jsonIn = org.json.JSONObject.quote(learnedIn)
        val jsonSend = org.json.JSONObject.quote(learnedSend)
        val jsonTxn = org.json.JSONObject.quote(txn)
        return """
(function(){
  if (window.__omniObs) { try { window.__omniObs.disconnect(); } catch(e){} window.__omniObs=null; }
  if (window.__omniTimer) { try { clearInterval(window.__omniTimer); } catch(e){} window.__omniTimer=null; }
  window.__omniRunning = true;
  var MSG = $jsonMsg;
  var LEARNED_IN = $jsonIn;
  var LEARNED_SEND = $jsonSend;
  var TXN = $jsonTxn;

  function state(s){ try{ OmniBridge.onState(s); }catch(e){} }
  function fail(t){
    window.__omniRunning=false;
    if(window.__omniObs){try{window.__omniObs.disconnect()}catch(e){} window.__omniObs=null;}
    if(window.__omniTimer){clearInterval(window.__omniTimer);window.__omniTimer=null;}
    try{ OmniBridge.onReply('ERR:'+t); }catch(e){}
  }
  function ok(t){
    window.__omniRunning=false;
    if(window.__omniObs){try{window.__omniObs.disconnect()}catch(e){} window.__omniObs=null;}
    if(window.__omniTimer){clearInterval(window.__omniTimer);window.__omniTimer=null;}
    try{ OmniBridge.onReply(t); }catch(e){}
  }
  function learn(i,s){ try{ OmniBridge.onLearn(i||'', s||''); }catch(e){} }
  function partial(t){ try{ OmniBridge.onPartial(t||''); }catch(e){} }

  function visible(el){
    if(!el) return false;
    var r = el.getBoundingClientRect();
    if(r.width < 4 || r.height < 4) return false;
    var st = window.getComputedStyle(el);
    if(st.display==='none' || st.visibility==='hidden' || parseFloat(st.opacity||'1')===0) return false;
    return true;
  }

  function needsAuth(){
    var body=(document.body&&document.body.innerText||'').slice(0,2500).toLowerCase();
    if(/sign in to continue|log in to continue|create an account|enter your password|verify your identity/.test(body)) return true;
    var pw=document.querySelector('input[type="password"]');
    return !!(pw && visible(pw));
  }

  function isGenerating(){
    var sels = [
      'button[aria-label*="Stop" i]','button[data-testid*="stop"]',
      '[aria-label*="Stop generating" i]','[data-testid="stop-button"]',
      '.result-streaming','.streaming'
    ];
    for(var i=0;i<sels.length;i++){
      try{
        var nodes=document.querySelectorAll(sels[i]);
        for(var j=0;j<nodes.length;j++){ if(visible(nodes[j])) return true; }
      }catch(e){}
    }
    return false;
  }

  function cssPath(el){
    if(!el || el.nodeType!==1) return '';
    if(el.id) return '#'+el.id;
    var dt = el.getAttribute('data-testid');
    if(dt) return '[data-testid="'+dt+'"]';
    var al = el.getAttribute('aria-label');
    if(al) return el.tagName.toLowerCase()+'[aria-label="'+String(al).replace(/"/g,'')+'"]';
    var parts=[], cur=el;
    for(var d=0; cur && cur.nodeType===1 && d<4; d++){
      var name=cur.tagName.toLowerCase();
      var parent=cur.parentElement;
      if(parent){
        var sibs=[].filter.call(parent.children,function(c){return c.tagName===cur.tagName;});
        if(sibs.length>1) name+=':nth-of-type('+([].indexOf.call(sibs,cur)+1)+')';
      }
      parts.unshift(name); cur=parent;
    }
    return parts.join(' > ');
  }

  function scoreInput(el){
    var s=0, r=el.getBoundingClientRect();
    var tag=(el.tagName||'').toLowerCase();
    var ph=((el.getAttribute('placeholder')||'')+' '+(el.getAttribute('aria-label')||'')+' '+(el.getAttribute('data-testid')||'')+' '+(el.id||'')+' '+(el.className||'')).toLowerCase();
    if(tag==='textarea') s+=35;
    if(el.isContentEditable||el.getAttribute('contenteditable')==='true') s+=32;
    if(el.getAttribute('role')==='textbox') s+=30;
    if(el.id==='prompt-textarea') s+=50;
    if(/prompt-textarea|composer|chat-input|prosemirror|ask|query/.test(ph)) s+=40;
    if(r.width>120) s+=12;
    if(r.top>(window.innerHeight||800)*0.25) s+=18;
    if(/message|ask|prompt|chat|send a|type|write|question|search/.test(ph)) s+=18;
    if(/search|email|password|username/.test(ph) && !/ask|chat|message/.test(ph)) s-=40;
    if(!visible(el)) s-=100;
    if(el.disabled) s-=50;
    return s;
  }

  function findInput(){
    try{
      var fixed=document.querySelector('#prompt-textarea,textarea[data-id],div.ProseMirror[contenteditable="true"],div[contenteditable="true"][data-lexical-editor]');
      if(fixed&&visible(fixed)&&scoreInput(fixed)>=8) return fixed;
    }catch(e){}
    if(LEARNED_IN){
      try{ var le=document.querySelector(LEARNED_IN); if(le&&visible(le)&&scoreInput(le)>=5) return le; }catch(e){}
    }
    var nodes=[].slice.call(document.querySelectorAll(
      'textarea,[contenteditable="true"],div[role="textbox"],#prompt-textarea,p[data-placeholder],input[type="text"],input:not([type]),[data-lexical-editor]'
    ));
    var best=null, bestScore=-999;
    nodes.forEach(function(el){ var sc=scoreInput(el); if(sc>bestScore){bestScore=sc;best=el;} });
    return (best&&bestScore>=8)?best:null;
  }

  function findSendSpatial(input){
    var ir=input.getBoundingClientRect(), cx=ir.right, cy=(ir.top+ir.bottom)/2;
    var candidates=[].slice.call(document.querySelectorAll('button,[role="button"],input[type="submit"],[data-testid*="send"],[aria-label*="Send" i]'));
    var best=null, bestScore=-1e9;
    candidates.forEach(function(el){
      if(!visible(el)) return;
      var r=el.getBoundingClientRect();
      if(r.width<8||r.height<8||r.width>240||r.height>100) return;
      var ex=(r.left+r.right)/2, ey=(r.top+r.bottom)/2;
      var dx=ex-cx, dy=Math.abs(ey-cy);
      var label=((el.getAttribute('aria-label')||'')+' '+(el.getAttribute('data-testid')||'')+' '+(el.className||'')+' '+(el.innerText||'')).toLowerCase();
      var score=0;
      if(dx>=-40&&dx<320) score+=80-dx*0.1; else score-=Math.abs(dx)*0.2;
      score-=dy*0.7;
      if(/send|submit|arrow|paper|airplane|reply|ask/.test(label)) score+=70;
      if(/stop|cancel|attach|upload|mic|voice|image|file|plus|menu/.test(label)) score-=90;
      if(el.querySelector&&el.querySelector('svg')) score+=10;
      if(score>bestScore){bestScore=score;best=el;}
    });
    return bestScore>12?best:null;
  }

  function findSendByAttr(){
    if(LEARNED_SEND){
      try{ var le=document.querySelector(LEARNED_SEND); if(le&&visible(le)) return le; }catch(e){}
    }
    var sels=[
      '[data-testid="send-button"]','[data-testid*="send"]',
      'button[aria-label*="Send" i]','button[aria-label*="Submit" i]','button[aria-label*="Ask" i]',
      'button[type="submit"]','form button[type="submit"]'
    ];
    for(var i=0;i<sels.length;i++){
      try{ var el=document.querySelector(sels[i]); if(el&&visible(el)) return el; }catch(e){}
    }
    return null;
  }

  function isChromeLine(t){
    t=(t||'').trim(); if(!t) return true;
    return /^(chat|agent|new chat|sign in|sign up|log in|api|terms of service|privacy policy|deep think|max|generated by ai\.?|for reference only\.?|menu|settings|home|upgrade|subscribe)$/i.test(t);
  }

  function assistantNodes(){
    var sels=[
      '[data-message-author-role="assistant"]',
      '[data-role="assistant"]',
      '[data-testid*="assistant"]',
      '.markdown.prose',
      '.prose'
    ];
    var out=[];
    for(var s=0;s<sels.length;s++){
      var nodes=document.querySelectorAll(sels[s]);
      for(var i=0;i<nodes.length;i++) out.push(nodes[i]);
    }
    return out;
  }

  function lastAssistantText(){
    var nodes=assistantNodes();
    if(!nodes.length) return '';
    return (nodes[nodes.length-1].innerText||nodes[nodes.length-1].textContent||'').trim();
  }

  function pageCorpus(){
    var roots=[];
    var sels=['[data-message-author-role]','[data-testid*="conversation"]','main','[role="main"]','#__next','body'];
    for(var i=0;i<sels.length;i++){
      var n=document.querySelector(sels[i]);
      if(n&&(n.innerText||'').length>20){ roots.push(n); break; }
    }
    if(!roots.length) roots.push(document.body);
    var raw=(roots[0].innerText||roots[0].textContent||'');
    return raw.split(/\n+/).map(function(l){return l.trim();}).filter(function(l){return l&&!isChromeLine(l);}).join('\n');
  }

  function fireKey(el,type,key,code,keyCode){
    try{ el.dispatchEvent(new KeyboardEvent(type,{key:key,code:code,keyCode:keyCode,which:keyCode,bubbles:true,cancelable:true,composed:true})); }catch(e){}
  }
  function firePointer(el){
    ['pointerdown','mousedown','pointerup','mouseup','click'].forEach(function(t){
      try{
        var C=t.indexOf('pointer')===0?PointerEvent:MouseEvent;
        el.dispatchEvent(new C(t,{bubbles:true,cancelable:true,view:window,buttons:1}));
      }catch(e){ try{ el.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window})); }catch(e2){} }
    });
  }
  function readInputValue(el){
    if(!el) return '';
    if(el.isContentEditable||el.getAttribute('contenteditable')==='true'||el.getAttribute('role')==='textbox')
      return (el.innerText||el.textContent||'').trim();
    return (el.value||'').trim();
  }

  function fillAll(el,text){
    el.focus();
    try{ el.click(); }catch(e){}
    var isEd=el.isContentEditable||el.getAttribute('contenteditable')==='true'||el.getAttribute('role')==='textbox'||(el.classList&&el.classList.contains('ProseMirror'));
    try{
      if(isEd){
        try{
          var sel=window.getSelection();
          var range=document.createRange();
          range.selectNodeContents(el);
          sel.removeAllRanges();
          sel.addRange(range);
        }catch(e){}
        try{ document.execCommand('selectAll',false,null); }catch(e){}
        try{ document.execCommand('delete',false,null); }catch(e){}
        try{ el.dispatchEvent(new InputEvent('beforeinput',{bubbles:true,cancelable:true,inputType:'insertText',data:text})); }catch(e){}
        var okIns=false;
        try{ okIns=document.execCommand('insertText',false,text); }catch(e){}
        if(!okIns){
          try{ el.textContent=''; el.innerText=text; }catch(e){}
          try{ el.appendChild(document.createTextNode(text)); }catch(e){}
        }
        try{ el.dispatchEvent(new InputEvent('input',{bubbles:true,data:text,inputType:'insertText'})); }
        catch(e){ el.dispatchEvent(new Event('input',{bubbles:true})); }
        el.dispatchEvent(new Event('change',{bubbles:true}));
      } else {
        var proto=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;
        var desc=Object.getOwnPropertyDescriptor(proto,'value');
        if(desc&&desc.set) desc.set.call(el,text); else el.value=text;
        try{ el.dispatchEvent(new InputEvent('input',{bubbles:true,data:text,inputType:'insertText'})); }
        catch(e){ el.dispatchEvent(new Event('input',{bubbles:true})); }
        el.dispatchEvent(new Event('change',{bubbles:true}));
      }
    }catch(e){}
  }

  var lastSendEl=null;
  var sentOnce=false;
  function trySubmit(input){
    if(sentOnce) return true;
    var attempts=[];
    var a=findSendByAttr(); if(a) attempts.push(a);
    var b=findSendSpatial(input); if(b&&attempts.indexOf(b)<0) attempts.push(b);
    var form=input.closest&&input.closest('form');
    if(form){ try{ if(typeof form.requestSubmit==='function'){ form.requestSubmit(); lastSendEl=form; } }catch(e){} }
    for(var i=0;i<attempts.length;i++){
      var btn=attempts[i]; lastSendEl=btn;
      try{ btn.removeAttribute('disabled'); btn.disabled=false; btn.setAttribute('aria-disabled','false'); }catch(e){}
      firePointer(btn); try{ btn.click(); }catch(e){}
    }
    fireKey(input,'keydown','Enter','Enter',13);
    fireKey(input,'keypress','Enter','Enter',13);
    fireKey(input,'keyup','Enter','Enter',13);
    try{ input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true,ctrlKey:true})); }catch(e){}
    sentOnce=true;
    return true;
  }

  state('PREPARING');
  if(needsAuth()){
    fail('Not signed in. Providers → Sign in on the chat page → Back.');
    return;
  }

  var input=findInput();
  if(!input){
    fail('COMPOSER_NOT_FOUND. Open Providers → Sign in → wait until the chat box is visible → Back.');
    return;
  }
  state('COMPOSER_FOUND');

  var beforeCorpus = pageCorpus();
  var beforeAssist = lastAssistantText();
  var beforeAssistCount = assistantNodes().length;

  fillAll(input, MSG);
  state('TEXT_ENTERED');

  function textAccepted(){
    var typed = readInputValue(input);
    if(!typed) return false;
    var snip = MSG.slice(0, Math.min(8, MSG.length));
    if(snip && typed.indexOf(snip) >= 0) return true;
    var a=typed.replace(/\s+/g,' ').toLowerCase();
    var b=MSG.replace(/\s+/g,' ').toLowerCase();
    return a.indexOf(b.slice(0, Math.min(12, b.length))) >= 0;
  }

  if(!textAccepted()) fillAll(input, MSG);
  if(!textAccepted()){
    try{ input.focus(); document.execCommand('selectAll',false,null); document.execCommand('insertText',false,MSG); }catch(e){}
  }
  if(!textAccepted()){
    fail('TEXT_NOT_ACCEPTED — composer did not take the message. Focus the real chat box on the provider page.');
    return;
  }
  state('TEXT_VERIFIED');

  state('SENDING');
  trySubmit(input);

  var confirmTries=0;
  function confirmSend(done){
    confirmTries++;
    var left=readInputValue(input);
    var snippet=MSG.slice(0, Math.min(16, MSG.length));
    var stillThere = left && snippet && left.indexOf(snippet) >= 0;
    var gen = isGenerating();
    var corpus=pageCorpus();
    var appeared = snippet && corpus.indexOf(snippet)>=0 && (beforeCorpus.indexOf(snippet)<0 || gen);
    var assistGrew = assistantNodes().length > beforeAssistCount;
    if(!stillThere || gen || appeared || assistGrew){
      state('SEND_CONFIRMED');
      done(true);
      return;
    }
    if(confirmTries===1){
      sentOnce=false;
      trySubmit(input);
      setTimeout(function(){ confirmSend(done); }, 180);
      return;
    }
    if(confirmTries>=4){ done(false); return; }
    setTimeout(function(){ confirmSend(done); }, 120);
  }

  confirmSend(function(sent){
    if(!sent){
      fail('SEND_NOT_CONFIRMED — message still in the input. Focus the real chat composer and retry.');
      return;
    }

    state('THINKING');
    var lastEmitted='';
    var lastSeen='';
    var quietTicks=0;
    var hadGrowth=false;
    var startMs=Date.now();

    function currentDelta(){
      var nodes=assistantNodes();
      var delta='';
      if(nodes.length > beforeAssistCount){
        var last=nodes[nodes.length-1];
        delta=(last.innerText||last.textContent||'').trim();
      } else {
        var assist=lastAssistantText();
        if(assist && assist.length > (beforeAssist||'').length + 1){
          if(beforeAssist && assist.indexOf(beforeAssist)===0) delta=assist.slice(beforeAssist.length).trim();
          else if(assist !== beforeAssist) delta=assist;
        }
        if(delta.length<2){
          var after=pageCorpus();
          if(after.length>beforeCorpus.length && after.indexOf(beforeCorpus)===0)
            delta=after.slice(beforeCorpus.length).trim();
        }
      }
      if(delta.indexOf(MSG)===0) delta=delta.slice(MSG.length).trim();
      return delta;
    }

    function maybeEmit(delta){
      if(delta && delta.length>1 && delta!==lastEmitted){
        lastEmitted=delta;
        state('WRITING');
        partial(delta);
        hadGrowth=true;
      }
    }

    function tryFinish(){
      var delta=currentDelta();
      maybeEmit(delta);
      var gen=isGenerating();
      if(gen){ quietTicks=0; return false; }
      if(delta && delta===lastSeen) quietTicks++; else { quietTicks=0; lastSeen=delta||''; }
      if(hadGrowth && quietTicks>=3 && !gen){
        state('DONE');
        learn(cssPath(input), cssPath(lastSendEl));
        ok(delta||lastEmitted);
        return true;
      }
      return false;
    }

    try{
      var root=document.querySelector('main,[role="main"],[data-testid*="conversation"],#__next')||document.body;
      window.__omniObs=new MutationObserver(function(){ tryFinish(); });
      window.__omniObs.observe(root,{childList:true,subtree:true,characterData:true});
    }catch(e){}

    window.__omniTimer=setInterval(function(){
      if(tryFinish()) return;
      if(Date.now()-startMs > 170000){
        clearInterval(window.__omniTimer); window.__omniTimer=null;
        if(window.__omniObs){try{window.__omniObs.disconnect()}catch(e){} window.__omniObs=null;}
        if(lastEmitted.length>1){ learn(cssPath(input), cssPath(lastSendEl)); ok(lastEmitted); }
        else fail('REPLY_TIMEOUT (txn '+TXN+')');
      }
    }, 150);
  });
})();
        """.trimIndent()
    }
}
