package com.omnihub.source.core

import android.annotation.SuppressLint
import android.content.Context
import android.os.Handler
import android.os.Looper
import android.util.Log
import android.webkit.JavascriptInterface
import kotlinx.coroutines.suspendCancellableCoroutine
import java.util.UUID
import kotlin.coroutines.resume

/**
 * WebRelay 1.0.9.7 — universal evidence path (all providers)
 *
 * SEND: confirmed only when conversation fingerprint shows the user turn
 *       and/or generating UI — never "we clicked".
 * REPLY: primary = new text after baseline in conversation region;
 *        role/class selectors are boosts only, not the only path.
 */
object WebViewChatEngine {

    data class Result(val text: String, val ok: Boolean, val transactionId: String = "")

    private const val TAG = "WEB"

    private val CHROME_LINE = Regex(
        """^(chat|agent|new chat|sign in|sign up|log in|api|terms of service|privacy policy|deep think|max|generated by ai\.?|for reference only\.?|glm[-\d.a-z]+|what can i build|menu|settings|home|upgrade|subscribe|download app|get the app|share|copy|regenerate|continue|stop generating)$""",
        RegexOption.IGNORE_CASE
    )

    fun cleanReply(raw: String, userMessage: String): String? {
        var text = raw.trim()
        val um = userMessage.trim()
        if (um.isNotEmpty() && text.startsWith(um)) text = text.removePrefix(um).trim()
        // Drop leading echo of user message mid-string once
        if (um.length >= 2) {
            val idx = text.indexOf(um)
            if (idx in 0..40) text = text.removeRange(idx, idx + um.length).trim()
        }
        val lines = text.lines().map { it.trim() }.filter { it.isNotEmpty() }
        val filtered = lines.filterNot { CHROME_LINE.matches(it) }
            .filterNot { it.equals(um, ignoreCase = true) }
        text = filtered.joinToString("\n").trim()
        if (text.isEmpty()) return null
        val lower = text.lowercase()
        val chromeHits = listOf(
            "terms of service", "privacy policy", "sign in", "new chat",
            "generated by ai", "for reference only"
        ).count { it in lower }
        if (chromeHits >= 2 && text.length < 400) return null
        return text
    }

    suspend fun send(
        context: Context,
        siteUrl: String,
        providerId: String,
        userMessage: String,
        timeoutMs: Long = 90_000L,
        onPartial: (String) -> Unit = {}
    ): Result = ProviderRelayQueue.withProviderLock(providerId) { queueWaitMs ->
        sendExclusive(context, siteUrl, providerId, userMessage, timeoutMs, queueWaitMs, onPartial)
    }

    @SuppressLint("SetJavaScriptEnabled")
    private suspend fun sendExclusive(
        context: Context,
        siteUrl: String,
        providerId: String,
        userMessage: String,
        timeoutMs: Long,
        queueWaitMs: Long,
        onPartial: (String) -> Unit
    ): Result = suspendCancellableCoroutine { cont ->
        val main = Handler(Looper.getMainLooper())
        val appCtx = context.applicationContext
        val txn = UUID.randomUUID().toString().take(8).uppercase()
        val t0 = System.currentTimeMillis()
        val pageMap = ProviderPageMap.load(appCtx, providerId)
        val target = siteUrl.ifBlank {
            ProviderCatalog.urlFor(providerId) ?: "https://chatgpt.com/"
        }

        Log.i(TAG, "[$txn] START provider=$providerId queueWaitMs=$queueWaitMs")

        main.post {
            val session = WarmSessionPool.getOrCreate(appCtx, providerId)
            session.busy = true
            session.lastTransactionId = txn
            session.lastUsedAt = System.currentTimeMillis()
            val web = session.web
            var finished = false
            var injected = false
            var firstTokenAt = 0L
            var sendConfirmedAt = 0L

            lateinit var timeoutRunnable: Runnable

            fun complete(text: String, ok: Boolean) {
                if (finished) return
                finished = true
                session.busy = false
                try { main.removeCallbacks(timeoutRunnable) } catch (_: Exception) {}
                try {
                    web.evaluateJavascript(
                        "(function(){window.__omniRunning=false;" +
                            "if(window.__omniObs){try{window.__omniObs.disconnect()}catch(e){}window.__omniObs=null;}" +
                            "if(window.__omniTimer){clearInterval(window.__omniTimer);window.__omniTimer=null;}})();",
                        null
                    )
                } catch (_: Exception) {}
                if (!ok) ProviderPageMap.rememberFailure(appCtx, providerId)
                val total = System.currentTimeMillis() - t0
                Log.i(
                    TAG,
                    "[$txn] ${if (ok) "OK" else "FAIL"} len=${text.length} totalMs=$total " +
                        "sendMs=${if (sendConfirmedAt > 0) sendConfirmedAt - t0 else -1} " +
                        "firstTokenMs=${if (firstTokenAt > 0) firstTokenAt - t0 else -1}"
                )
                if (cont.isActive) cont.resume(Result(text, ok, txn))
            }

            // Last-resort: any substantial new page text (structure-agnostic salvage)
            timeoutRunnable = Runnable {
                web.evaluateJavascript(
                    """
                    (function(){
                      var root=document.querySelector('main,[role=main],[data-testid*=conversation],#__next')||document.body;
                      var t=(root&&root.innerText||'').trim();
                      return t.slice(-8000);
                    })();
                    """.trimIndent()
                ) { last ->
                    val t = last?.trim()?.removeSurrounding("\"")
                        ?.replace("\\n", "\n")?.replace("\\\"", "\"")?.trim().orEmpty()
                    val cleaned = cleanReply(t, userMessage)
                    if (cleaned != null && cleaned.length > 12) {
                        complete(ReplySanitizer.strip(cleaned).ifBlank { cleaned }, true)
                    } else if (t.length > 80) {
                        // Prefer tail after user message if present
                        val um = userMessage.trim()
                        val idx = t.lastIndexOf(um)
                        val tail = if (idx >= 0) t.substring(idx + um.length).trim() else t.takeLast(2000)
                        val c2 = cleanReply(tail, userMessage)
                        if (c2 != null && c2.length > 8) {
                            complete(ReplySanitizer.strip(c2).ifBlank { c2 }, true)
                        } else {
                            complete("REPLY_TIMEOUT txn $txn — no verified reply after baseline. Stay on chat and retry.", false)
                        }
                    } else {
                        complete("REPLY_TIMEOUT txn $txn — no verified reply after baseline. Stay on chat and retry.", false)
                    }
                }
            }

            val bridgeName = "OmniBridge"
            try { web.removeJavascriptInterface(bridgeName) } catch (_: Exception) {}

            val bridge = object {
                @JavascriptInterface
                fun onReply(text: String) {
                    main.post {
                        val t = text.trim()
                        when {
                            t.startsWith("ERR:") ->
                                complete(t.removePrefix("ERR:").ifBlank { "Page error" }, false)
                            t.isBlank() -> complete("Empty reply.", false)
                            else -> {
                                val cleaned = cleanReply(t, userMessage) ?: t
                                complete(ReplySanitizer.strip(cleaned).ifBlank { cleaned }, true)
                            }
                        }
                    }
                }

                @JavascriptInterface
                fun onLearn(inputSel: String?, sendSel: String?, convSel: String?) {
                    main.post {
                        ProviderPageMap.rememberSuccess(appCtx, providerId, inputSel, sendSel, convSel)
                    }
                }

                @JavascriptInterface
                fun onPartial(text: String) {
                    main.post {
                        if (finished) return@post
                        val raw = text.trim()
                        if (raw.isEmpty() || raw.startsWith("ERR:")) return@post
                        if (firstTokenAt == 0L) {
                            firstTokenAt = System.currentTimeMillis()
                            Log.i(TAG, "[$txn] FIRST_TOKEN +${firstTokenAt - t0}ms")
                        }
                        val cleaned = cleanReply(raw, userMessage) ?: raw
                        val stripped = ReplySanitizer.strip(cleaned)
                        if (stripped.isNotBlank()) onPartial(stripped)
                    }
                }

                @JavascriptInterface
                fun onState(state: String) {
                    val now = System.currentTimeMillis()
                    if (state == "SEND_CONFIRMED" && sendConfirmedAt == 0L) sendConfirmedAt = now
                    Log.i(TAG, "[$txn] $state +${now - t0}ms")
                }
            }
            web.addJavascriptInterface(bridge, bridgeName)

            cont.invokeOnCancellation {
                main.post {
                    session.busy = false
                    if (!finished) complete("Cancelled", false)
                }
            }

            main.postDelayed(timeoutRunnable, timeoutMs)

            fun inject() {
                if (finished || injected) return
                injected = true
                web.evaluateJavascript(
                    "(function(){window.__omniRunning=false;" +
                        "if(window.__omniObs){try{window.__omniObs.disconnect()}catch(e){}window.__omniObs=null;}" +
                        "if(window.__omniTimer){clearInterval(window.__omniTimer);window.__omniTimer=null;}})();",
                    null
                )
                main.post {
                    if (finished) return@post
                    web.evaluateJavascript(
                        buildEngineScript(
                            userMessage,
                            pageMap.composer,
                            pageMap.send,
                            pageMap.conversation,
                            txn
                        ),
                        null
                    )
                }
            }

            fun waitComposer(attempt: Int) {
                if (finished || injected) return
                val cSel = pageMap.composer
                val learnedBit = if (cSel.isNotBlank())
                    "try{var le=document.querySelector(${org.json.JSONObject.quote(cSel)});if(le)learned=true;}catch(e){}"
                else ""
                web.evaluateJavascript(
                    "(function(){var learned=false;$learnedBit" +
                        "var n=document.querySelectorAll('#prompt-textarea,textarea,[contenteditable=true],div[role=textbox],.ProseMirror').length;" +
                        "var body=(document.body&&document.body.innerText||'').slice(0,900).toLowerCase();" +
                        "var auth=/sign in to continue|log in to continue|create an account|enter your password/.test(body);" +
                        "var pw=!!document.querySelector('input[type=password]');" +
                        "return (learned?1:0)+':'+n+':'+(auth||pw?1:0);})();"
                ) { s ->
                    val p = (s ?: "0:0:0").replace("\"", "").trim().split(":")
                    val learned = p.getOrNull(0)?.toIntOrNull() == 1
                    val n = p.getOrNull(1)?.toIntOrNull() ?: 0
                    val auth = p.getOrNull(2)?.toIntOrNull() == 1
                    if (auth && n == 0 && !learned) {
                        complete("AUTH_REQUIRED — open provider, sign in, stay on chat box, then retry.", false)
                        return@evaluateJavascript
                    }
                    if (learned || n > 0) inject()
                    else if (attempt >= 12) inject()
                    else main.postDelayed({ waitComposer(attempt + 1) }, 80)
                }
            }

            val sameHost = try {
                val a = java.net.URI(target).host?.lowercase().orEmpty()
                val b = java.net.URI(session.lastUrl.ifBlank { "http://local" }).host?.lowercase().orEmpty()
                a.isNotBlank() && (a == b || b.endsWith(a) || a.endsWith(b))
            } catch (_: Exception) {
                false
            }

            if (session.ready && sameHost && session.lastUrl.isNotBlank()) {
                Log.i(TAG, "[$txn] HOT_PATH")
                waitComposer(0)
            } else {
                session.ready = false
                Log.i(TAG, "[$txn] COLD_LOAD")
                web.webViewClient = object : android.webkit.WebViewClient() {
                    override fun onPageFinished(view: android.webkit.WebView?, url: String?) {
                        session.lastUrl = url.orEmpty()
                        session.ready = true
                        main.post { waitComposer(0) }
                    }
                }
                web.loadUrl(target)
            }
        }
    }

    private fun buildEngineScript(
        message: String,
        mapComposer: String,
        mapSend: String,
        mapConv: String,
        txn: String
    ): String {
        val jsonMsg = org.json.JSONObject.quote(message)
        val jsonIn = org.json.JSONObject.quote(mapComposer)
        val jsonSend = org.json.JSONObject.quote(mapSend)
        val jsonConv = org.json.JSONObject.quote(mapConv)
        val jsonTxn = org.json.JSONObject.quote(txn)
        return """
(function(){
  if (window.__omniObs) { try { window.__omniObs.disconnect(); } catch(e){} window.__omniObs=null; }
  if (window.__omniTimer) { try { clearInterval(window.__omniTimer); } catch(e){} window.__omniTimer=null; }
  window.__omniRunning = true;
  var MSG = $jsonMsg;
  var MAP_IN = $jsonIn;
  var MAP_SEND = $jsonSend;
  var MAP_CONV = $jsonConv;
  var TXN = $jsonTxn;

  function state(s){ try{ OmniBridge.onState(s); }catch(e){} }
  function fail(t){
    window.__omniRunning=false;
    if(window.__omniObs){try{window.__omniObs.disconnect()}catch(e){}window.__omniObs=null;}
    if(window.__omniTimer){clearInterval(window.__omniTimer);window.__omniTimer=null;}
    try{ OmniBridge.onReply('ERR:'+t); }catch(e){}
  }
  function ok(t){
    window.__omniRunning=false;
    if(window.__omniObs){try{window.__omniObs.disconnect()}catch(e){}window.__omniObs=null;}
    if(window.__omniTimer){clearInterval(window.__omniTimer);window.__omniTimer=null;}
    try{ OmniBridge.onReply(t); }catch(e){}
  }
  function learn(i,s,c){ try{ OmniBridge.onLearn(i||'',s||'',c||''); }catch(e){} }
  function partial(t){ try{ OmniBridge.onPartial(t||''); }catch(e){} }

  function visible(el){
    if(!el) return false;
    var r=el.getBoundingClientRect();
    if(r.width<3||r.height<3) return false;
    var st=window.getComputedStyle(el);
    return st.display!=='none' && st.visibility!=='hidden' && parseFloat(st.opacity||'1')!==0;
  }

  function needsAuth(){
    var body=(document.body&&document.body.innerText||'').slice(0,2000).toLowerCase();
    if(/sign in to continue|log in to continue|create an account|enter your password/.test(body)) return true;
    var pw=document.querySelector('input[type="password"]');
    return !!(pw&&visible(pw));
  }

  function isGenerating(){
    var sels=[
      'button[aria-label*="Stop" i]','button[data-testid*="stop"]','[data-testid="stop-button"]',
      'button[aria-label*="Stop generating" i]','.result-streaming','.streaming',
      '[data-testid="stop-button"]','button:has(svg[class*="stop"])'
    ];
    for(var i=0;i<sels.length;i++){
      try{ var n=document.querySelectorAll(sels[i]); for(var j=0;j<n.length;j++) if(visible(n[j])) return true; }catch(e){}
    }
    // Textual generating hints (universal)
    try{
      var t=(document.body&&document.body.innerText||'').slice(-1200).toLowerCase();
      if(/stop generating|generating…|generating\.\.\.|thinking…|thinking\.\.\./.test(t)) return true;
    }catch(e){}
    return false;
  }

  function cssPath(el){
    if(!el||el.nodeType!==1) return '';
    if(el.id) return '#'+el.id;
    var dt=el.getAttribute('data-testid'); if(dt) return '[data-testid="'+dt+'"]';
    var al=el.getAttribute('aria-label');
    if(al) return el.tagName.toLowerCase()+'[aria-label="'+String(al).replace(/"/g,'')+'"]';
    var parts=[], cur=el;
    for(var d=0;cur&&cur.nodeType===1&&d<4;d++){
      var name=cur.tagName.toLowerCase(), parent=cur.parentElement;
      if(parent){
        var sibs=[].filter.call(parent.children,function(c){return c.tagName===cur.tagName;});
        if(sibs.length>1) name+=':nth-of-type('+([].indexOf.call(sibs,cur)+1)+')';
      }
      parts.unshift(name); cur=parent;
    }
    return parts.join(' > ');
  }

  function scoreInput(el){
    var s=0,r=el.getBoundingClientRect();
    var ph=((el.getAttribute('placeholder')||'')+' '+(el.getAttribute('aria-label')||'')+' '+(el.getAttribute('data-testid')||'')+' '+(el.id||'')+' '+(el.className||'')).toLowerCase();
    var tag=(el.tagName||'').toLowerCase();
    if(el.id==='prompt-textarea') s+=60;
    if(tag==='textarea') s+=35;
    if(el.isContentEditable||el.getAttribute('contenteditable')==='true') s+=34;
    if(el.getAttribute('role')==='textbox') s+=30;
    if(/prompt-textarea|composer|chat-input|prosemirror|ask anything|message|message chatgpt/.test(ph)) s+=45;
    if(r.width>80) s+=10;
    if(r.top>(window.innerHeight||800)*0.15) s+=20;
    if(r.bottom>(window.innerHeight||800)*0.5) s+=15;
    if(/search(?!.*chat)|email|password|username/.test(ph)) s-=60;
    if(!visible(el)) s-=120;
    if(el.disabled) s-=50;
    return s;
  }

  function findInput(){
    var preferred=[
      '#prompt-textarea',
      'textarea[data-id]',
      'div.ProseMirror[contenteditable="true"]',
      'div[contenteditable="true"][data-lexical-editor]',
      '[data-testid="composer"] textarea',
      '[data-testid="composer"] [contenteditable="true"]',
      'div[contenteditable="true"]'
    ];
    for(var i=0;i<preferred.length;i++){
      try{
        var els=document.querySelectorAll(preferred[i]);
        for(var k=0;k<els.length;k++){
          if(visible(els[k])&&scoreInput(els[k])>=8) return els[k];
        }
      }catch(e){}
    }
    if(MAP_IN){
      try{ var le=document.querySelector(MAP_IN); if(le&&visible(le)&&scoreInput(le)>=5) return le; }catch(e){}
    }
    var nodes=[].slice.call(document.querySelectorAll(
      'textarea,[contenteditable="true"],div[role="textbox"],#prompt-textarea,input[type="text"],input:not([type]),[data-lexical-editor]'
    ));
    var best=null,bestScore=-999;
    nodes.forEach(function(el){ var sc=scoreInput(el); if(sc>bestScore){bestScore=sc;best=el;} });
    return (best&&bestScore>=10)?best:null;
  }

  function findSend(input){
    if(MAP_SEND){
      try{ var le=document.querySelector(MAP_SEND); if(le&&visible(le)) return le; }catch(e){}
    }
    var sels=[
      '[data-testid="send-button"]','[data-testid*="send"]',
      'button[data-testid="send-button"]',
      'button[aria-label*="Send" i]','button[aria-label*="Submit" i]','button[aria-label*="Ask" i]',
      'button[type="submit"]'
    ];
    for(var i=0;i<sels.length;i++){
      try{
        var nodes=document.querySelectorAll(sels[i]);
        for(var j=0;j<nodes.length;j++) if(visible(nodes[j])) return nodes[j];
      }catch(e){}
    }
    var ir=input.getBoundingClientRect(), cx=ir.right, cy=(ir.top+ir.bottom)/2;
    var best=null,bestScore=-1e9;
    [].slice.call(document.querySelectorAll('button,[role="button"],a[role="button"]')).forEach(function(el){
      if(!visible(el)) return;
      var r=el.getBoundingClientRect();
      if(r.width<8||r.height<8||r.width>280||r.height>120) return;
      var dx=(r.left+r.right)/2-cx, dy=Math.abs((r.top+r.bottom)/2-cy);
      var label=((el.getAttribute('aria-label')||'')+(el.getAttribute('data-testid')||'')+(el.innerText||'')+(el.className||'')).toLowerCase();
      var score=0;
      if(dx>=-50&&dx<360) score+=90-Math.abs(dx)*0.12; else score-=Math.abs(dx)*0.25;
      score-=dy*0.8;
      if(/send|submit|arrow|paper|airplane|ask/.test(label)) score+=75;
      if(/stop|cancel|attach|upload|mic|file|plus|menu|voice|photo/.test(label)) score-=100;
      if(score>bestScore){bestScore=score;best=el;}
    });
    return bestScore>15?best:null;
  }

  function convRoot(){
    if(MAP_CONV){
      try{ var el=document.querySelector(MAP_CONV); if(el) return el; }catch(e){}
    }
    var sels=[
      '[data-testid*="conversation"]','[class*="Conversation"]',
      'main','[role="main"]','#__next','[class*="chat"]','body'
    ];
    for(var i=0;i<sels.length;i++){
      try{ var n=document.querySelector(sels[i]); if(n&&(n.innerText||'').length>8) return n; }catch(e){}
    }
    return document.body;
  }

  /** Universal fingerprint of conversation text (provider-agnostic). */
  function fingerprint(){
    var root=convRoot();
    var raw=(root.innerText||root.textContent||'').replace(/\r/g,'');
    // Normalize whitespace; keep content order
    return raw.split('\n').map(function(l){return l.trim();}).filter(function(l){
      if(!l) return false;
      if(/^(chat|agent|new chat|sign in|log in|terms of service|privacy policy|menu|settings|home|share|copy)$/i.test(l)) return false;
      return true;
    }).join('\n');
  }

  function assistantBoostText(){
    var n=[].slice.call(document.querySelectorAll(
      '[data-message-author-role="assistant"],[data-role="assistant"],[data-testid*="assistant"],.markdown.prose,.prose'
    ));
    if(!n.length) return '';
    return (n[n.length-1].innerText||n[n.length-1].textContent||'').trim();
  }

  function readVal(el){
    if(!el) return '';
    if(el.isContentEditable||el.getAttribute('contenteditable')==='true'||el.getAttribute('role')==='textbox'||(el.classList&&el.classList.contains('ProseMirror')))
      return (el.innerText||el.textContent||'').trim();
    return (el.value||'').trim();
  }

  function fill(el,text){
    try{ el.scrollIntoView({block:'center',inline:'nearest'}); }catch(e){}
    el.focus();
    try{ el.click(); }catch(e){}
    var isEd=el.isContentEditable||el.getAttribute('contenteditable')==='true'||el.getAttribute('role')==='textbox'||(el.classList&&el.classList.contains('ProseMirror'));
    try{
      if(isEd){
        try{
          var sel=window.getSelection();
          var range=document.createRange();
          range.selectNodeContents(el);
          sel.removeAllRanges();
          sel.addRange(range);
        }catch(e){}
        try{ document.execCommand('selectAll',false,null); }catch(e){}
        try{ document.execCommand('delete',false,null); }catch(e){}
        try{ el.dispatchEvent(new InputEvent('beforeinput',{bubbles:true,cancelable:true,composed:true,inputType:'insertText',data:text})); }catch(e){}
        var okIns=false;
        try{ okIns=document.execCommand('insertText',false,text); }catch(e){}
        if(!okIns){ try{ el.textContent=''; el.innerText=text; }catch(e){} }
        try{ el.dispatchEvent(new InputEvent('input',{bubbles:true,composed:true,data:text,inputType:'insertText'})); }
        catch(e){ el.dispatchEvent(new Event('input',{bubbles:true})); }
        el.dispatchEvent(new Event('change',{bubbles:true}));
        el.dispatchEvent(new Event('keyup',{bubbles:true}));
      } else {
        var proto=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;
        var desc=Object.getOwnPropertyDescriptor(proto,'value');
        if(desc&&desc.set) desc.set.call(el,text); else el.value=text;
        try{ el.dispatchEvent(new InputEvent('input',{bubbles:true,data:text,inputType:'insertText'})); }
        catch(e){ el.dispatchEvent(new Event('input',{bubbles:true})); }
        el.dispatchEvent(new Event('change',{bubbles:true}));
      }
    }catch(e){}
  }

  function firePointer(el){
    if(!el) return;
    try{ el.removeAttribute('disabled'); el.disabled=false; el.setAttribute('aria-disabled','false'); }catch(e){}
    ['pointerover','pointerenter','pointerdown','mousedown','pointerup','mouseup','click'].forEach(function(t){
      try{
        var C=t.indexOf('pointer')===0?PointerEvent:MouseEvent;
        el.dispatchEvent(new C(t,{bubbles:true,cancelable:true,view:window,buttons:1,composed:true}));
      }catch(e){ try{ el.click(); }catch(e2){} }
    });
    try{ el.click(); }catch(e){}
  }
  function fireEnter(el){
    try{
      el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true,cancelable:true,composed:true}));
      el.dispatchEvent(new KeyboardEvent('keypress',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true,cancelable:true}));
      el.dispatchEvent(new KeyboardEvent('keyup',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true,composed:true}));
    }catch(e){}
  }

  function accepted(el){
    var v=readVal(el);
    if(!v) return false;
    var snip=MSG.slice(0, Math.min(8, MSG.length));
    if(snip && v.indexOf(snip)>=0) return true;
    var a=v.replace(/\s+/g,' ').toLowerCase();
    var b=MSG.replace(/\s+/g,' ').toLowerCase();
    return b.length>0 && a.indexOf(b.slice(0, Math.min(12, b.length)))>=0;
  }

  /** Evidence that the user turn landed in the conversation (universal). */
  function userTurnEvidence(beforeFp){
    var snip=MSG.slice(0, Math.min(24, MSG.length));
    if(!snip) return false;
    var after=fingerprint();
    if(beforeFp.indexOf(snip)<0 && after.indexOf(snip)>=0) return true;
    // Role boost (ChatGPT etc.)
    try{
      var users=document.querySelectorAll('[data-message-author-role="user"],[data-role="user"]');
      for(var i=0;i<users.length;i++){
        var t=(users[i].innerText||'').trim();
        if(t.indexOf(snip)>=0) return true;
      }
    }catch(e){}
    return false;
  }

  /** New assistant-ish content after baseline — structure-agnostic primary. */
  function deltaAfterBaseline(beforeFp){
    var after=fingerprint();
    var d='';
    if(after.length>beforeFp.length && after.indexOf(beforeFp)===0){
      d=after.slice(beforeFp.length).trim();
    } else if(after!==beforeFp){
      // Find longest shared prefix then take remainder
      var i=0, lim=Math.min(after.length, beforeFp.length);
      while(i<lim && after.charAt(i)===beforeFp.charAt(i)) i++;
      // Prefer suffix after user message if present
      var snip=MSG.slice(0, Math.min(20, MSG.length));
      var uIdx=after.lastIndexOf(snip);
      if(uIdx>=0){
        d=after.slice(uIdx+snip.length).trim();
      } else if(i<after.length){
        d=after.slice(i).trim();
      }
    }
    // Boost: role-based last assistant if longer/cleaner
    var boost=assistantBoostText();
    if(boost && boost.length>d.length && boost!==beforeFp){
      // only if boost is not the entire old page
      if(beforeFp.indexOf(boost)<0 || boost.length>40){
        if(d.length<8 || boost.indexOf(d)>=0 || d.indexOf(boost.slice(0,20))>=0) d=boost;
      }
    }
    // Strip leading user echo
    if(d.indexOf(MSG)===0) d=d.slice(MSG.length).trim();
    var snip2=MSG.slice(0, Math.min(16, MSG.length));
    if(snip2 && d.indexOf(snip2)===0) d=d.slice(snip2.length).trim();
    return d;
  }

  // ——— HOT PATH ———
  state('SESSION_READY');
  if(needsAuth()){ fail('AUTH_REQUIRED'); return; }

  var input=findInput();
  if(!input){ fail('COMPOSER_NOT_FOUND — open chat box on provider then retry'); return; }
  state('COMPOSER_RESOLVED');

  var beforeFp=fingerprint();
  state('BASELINE_CAPTURED');

  input.focus();
  state('COMPOSER_FOCUSED');
  fill(input, MSG);

  function verifyInput(attempt, cont){
    if(accepted(input)){ cont(true); return; }
    if(attempt===0){
      fill(input, MSG);
      setTimeout(function(){ verifyInput(1, cont); }, 60);
      return;
    }
    cont(false);
  }

  verifyInput(0, function(okInput){
    if(!okInput){
      fail('INPUT_FAILED — composer did not accept text. Open provider, tap real chat box, type once, Back, retry.');
      return;
    }
    state('INPUT_VERIFIED');

    var sendBtn=findSend(input);
    var lastSend=sendBtn;
    state('SENDING');

    function doSend(){
      if(sendBtn){
        firePointer(sendBtn);
      }
      fireEnter(input);
      try{
        var form=input.closest&&input.closest('form');
        if(form&&form.requestSubmit) form.requestSubmit();
        else if(form) form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));
      }catch(e){}
    }
    doSend();

    // Confirm window ~1.5s: evidence only (user turn in fingerprint / generating)
    var confirmTry=0;
    function confirmSend(done){
      confirmTry++;
      var gen=isGenerating();
      var turn=userTurnEvidence(beforeFp);
      var left=readVal(input);
      var snip=MSG.slice(0, Math.min(10, MSG.length));
      var cleared=!left || (snip && left.indexOf(snip)<0);
      // Strong evidence
      if(turn || gen){
        state('SEND_CONFIRMED');
        done(true);
        return;
      }
      // Soft: cleared after send often means accepted (ChatGPT sometimes)
      if(confirmTry>=4 && cleared && fingerprint()!==beforeFp){
        state('SEND_CONFIRMED');
        done(true);
        return;
      }
      if(confirmTry===1){
        doSend();
        setTimeout(function(){ confirmSend(done); }, 120);
        return;
      }
      if(confirmTry>=12){ done(false); return; } // ~1.5s
      setTimeout(function(){ confirmSend(done); }, 120);
    }

    confirmSend(function(sent){
      if(!sent){
        fail('SEND_FAILED — message not submitted. Stay on signed-in chat UI and retry.');
        return;
      }

      state('THINKING');
      var lastEmitted='';
      var lastSeen='';
      var quiet=0;
      var grew=false;
      var tStart=Date.now();

      function tick(){
        var d=deltaAfterBaseline(beforeFp);
        if(d && d.length>1 && d!==lastEmitted){
          lastEmitted=d;
          state('STREAMING');
          partial(d);
          grew=true;
        }
        var gen=isGenerating();
        if(gen){ quiet=0; return false; }
        if(d && d===lastSeen) quiet++; else { quiet=0; lastSeen=d||''; }
        // Complete when we have content, not generating, and text quiet
        if(grew && quiet>=3 && !gen && d.length>1){
          state('COMPLETED');
          learn(cssPath(input), cssPath(lastSend), cssPath(convRoot()));
          ok(d||lastEmitted);
          return true;
        }
        // If generating never showed but we got a solid delta and it stabilized
        if(grew && quiet>=5 && d.length>20 && !gen){
          state('COMPLETED');
          learn(cssPath(input), cssPath(lastSend), cssPath(convRoot()));
          ok(d||lastEmitted);
          return true;
        }
        return false;
      }

      try{
        window.__omniObs=new MutationObserver(function(){ tick(); });
        window.__omniObs.observe(convRoot(),{childList:true,subtree:true,characterData:true});
      }catch(e){}

      window.__omniTimer=setInterval(function(){
        if(tick()) return;
        if(Date.now()-tStart>85000){
          clearInterval(window.__omniTimer); window.__omniTimer=null;
          if(window.__omniObs){try{window.__omniObs.disconnect()}catch(e){}window.__omniObs=null;}
          var finalD=deltaAfterBaseline(beforeFp);
          if((finalD&&finalD.length>8) || lastEmitted.length>8){
            learn(cssPath(input), cssPath(lastSend), cssPath(convRoot()));
            ok(finalD||lastEmitted);
          } else fail('REPLY_TIMEOUT txn '+TXN+' — no verified reply after baseline');
        }
      }, 90);
    });
  });
})();
        """.trimIndent()
    }
}
